# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Mappy' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for Mappy
  pod 'Firebase/Core'

  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'

  pod 'Firebase/Auth'
  pod 'FirebaseFirestoreSwift'

  pod 'Kingfisher', '~> 5.0'
end
